### ISSUE TITLE
Error on response.

### ISSUE THREAD

**Issue by Razvan-Miereanu** [houjunchen/botkit-dashbot-apiai-facebook-sample#1]
The only response i'm getting on bot.reply is this:

`Server response error with status code: 400
{
  "id": "a76ea4cc-77a5-47f8-b2b2-7aeaca2c939d",
  "timestamp": "2016-11-18T16:17:36.698Z",
  "status": {
    "code": 400,
    "errorType": "bad_request",
    "errorDetails": "Required \u0027sessionId\u0027 parameter is empty."
  }
}`

Any suggestions/ideas on what i'm doing wrong?

`controller.on('message_received', function(bot, message) {
    console.log(message);
    var request = apiaibot.textRequest(message.text);
    request.on('response', function(response) {
        bot.reply(message, response.result.fulfillment.speech);
    });
    request.on('error', function(error) {
        console.log(error);
        bot.reply(message, error);
    });
    request.end();
});`

For example if i'm asking "when is your birthday?" which is matched by the domain Small talk i get the same error in the response as the one above. Thanks, Raz.

**Comment by houjunchen** [comment]
Hi Razvan,

Maybe you can check the value of `request` in 

```
var request = apiaibot.textRequest(message.text);
```

and the value of its `response`.

**Comment by Razvan-Miereanu** [comment]
I got it working by setting the sessionId parameter. Thank you!
